language: java

jdk:
  - oraclejdk8
  - openjdk8
  
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y openjfx
  
install: 
  - ant

script:
  - ant test

notifications:
  email:
    recipients:
      - vazquez.nicolas.daniel@gmail.com
      - elianagam2@gmail.com
      - jalbarracn@gmail.com
      - camilaserra5@gmail.com
    on_failure: always
