language: java

jdk:
  - oraclejdk8
  
install: 
  - ant

script:
  - ant test

notifications:
  email:
    recipients:
      - vazquez.nicolas.daniel@gmail.com
      - elianagam2@gmail.com
      - jalbarracn@gmail.com
      - camilaserra5@gmail.com
    on_failure: always
